# Generated by Django 5.2.10 on 2026-02-05 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dia_diem', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=200)),
                ('vi_do', models.FloatField()),
                ('kinh_do', models.FloatField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='dia_diem/')),
                ('mota', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sp', models.CharField(max_length=100)),
                ('gia', models.DecimalField(decimal_places=0, max_digits=10)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='san_pham/')),
            ],
        ),
        migrations.CreateModel(
            name='SanBong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san', models.CharField(max_length=50)),
                ('loai_san', models.CharField(choices=[('5', 'Sân 5'), ('7', 'Sân 7'), ('11', 'Sân 11')], default='5', max_length=10)),
                ('gia_tien', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vi_do', models.FloatField()),
                ('kinh_do', models.FloatField()),
                ('dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_san_con', to='quanlysan.diadiem')),
            ],
        ),
        migrations.CreateModel(
            name='DatSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=15)),
                ('ngay_dat', models.DateField()),
                ('gio_bat_dau', models.TimeField()),
                ('thoi_luong', models.IntegerField(default=60)),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tien_coc', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ Duyệt'), ('DA_DUYET', 'Đã Duyệt'), ('TU_CHOI', 'Hủy')], default='CHO_DUYET', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlysan.sanbong')),
                ('dich_vu_kem', models.ManyToManyField(blank=True, to='quanlysan.sanpham')),
            ],
        ),
    ]
