# Generated by Django 6.0.3 on 2026-05-20 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dia_diem', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('vi_do', models.FloatField(blank=True, null=True)),
                ('kinh_do', models.FloatField(blank=True, null=True)),
                ('hinh_anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='dia_diem/')),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('is_pin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThongTinGioiThieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de_hero', models.CharField(default='Về Chúng Tôi', max_length=255, verbose_name='Tiêu đề chính')),
                ('mo_ta_hero', models.TextField(default='Nền tảng đặt sân bóng đá tiện lợi...', verbose_name='Mô tả ngắn (Hero)')),
                ('hinh_anh_hero', models.ImageField(blank=True, null=True, upload_to='gioi_thieu/', verbose_name='Ảnh bìa trang (Hero Background)')),
                ('tam_nhin_su_menh', models.TextField(blank=True, null=True, verbose_name='Tầm nhìn & Sứ mệnh')),
                ('noi_dung_chinh', models.TextField(blank=True, null=True, verbose_name='Nội dung chi tiết')),
                ('hinh_anh_chinh', models.ImageField(blank=True, null=True, upload_to='gioi_thieu/', verbose_name='Ảnh minh họa nội dung')),
                ('feature_1_title', models.CharField(default='Nhanh chóng', max_length=100)),
                ('feature_1_desc', models.CharField(default='Đặt sân 24/7 chỉ với 30 giây.', max_length=255)),
                ('feature_2_title', models.CharField(default='Cáp kèo dễ dàng', max_length=100)),
                ('feature_2_desc', models.CharField(default='Hệ thống tìm đối thủ thông minh.', max_length=255)),
                ('feature_3_title', models.CharField(default='Uy tín 100%', max_length=100)),
                ('feature_3_desc', models.CharField(default='Cam kết giữ sân, không lo bị hủy.', max_length=255)),
                ('feature_4_title', models.CharField(default='Hỗ trợ tận tình', max_length=100)),
                ('feature_4_desc', models.CharField(default='Chăm sóc khách hàng liên tục.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.IntegerField(default=5)),
                ('binh_luan', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_danh_gia', to='quanlysan.diadiem')),
            ],
        ),
        migrations.CreateModel(
            name='HinhAnhDiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='dia_diem_gallery/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_hinh_anh', to='quanlysan.diadiem')),
            ],
        ),
        migrations.CreateModel(
            name='SanBong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san', models.CharField(max_length=50)),
                ('loai_san', models.IntegerField(choices=[(5, 'Sân 5 người'), (7, 'Sân 7 người'), (11, 'Sân 11 người')], default=5)),
                ('gia_tien', models.DecimalField(decimal_places=0, max_digits=10)),
                ('danh_muc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlysan.danhmucsan')),
                ('dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_san_con', to='quanlysan.diadiem')),
            ],
        ),
        migrations.CreateModel(
            name='DatSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=15)),
                ('ngay_dat', models.DateField()),
                ('gio_bat_dau', models.TimeField()),
                ('thoi_luong', models.IntegerField()),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tien_coc', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlysan.sanbong')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sp', models.CharField(max_length=100)),
                ('gia', models.DecimalField(decimal_places=0, max_digits=10)),
                ('so_luong', models.IntegerField(default=0)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='san_pham/')),
                ('dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kho_hang', to='quanlysan.diadiem')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_dat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_dv', to='quanlysan.datsan')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlysan.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='TimDoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_da', models.DateField(blank=True, null=True)),
                ('gio_bat_dau', models.TimeField(blank=True, null=True)),
                ('thoi_luong', models.IntegerField(default=60)),
                ('trinh_do', models.CharField(choices=[('YEU', 'Yếu'), ('TB', 'Trung bình'), ('KHA', 'Khá/Mạnh')], max_length=50)),
                ('sdt_lien_he', models.CharField(max_length=15)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('DANG_TIM', 'Đang tìm đối'), ('DA_CAP', 'Đã cáp kèo')], default='DANG_TIM', max_length=20)),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('doi_thu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keo_nhan', to=settings.AUTH_USER_MODEL)),
                ('nguoi_dang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keo_tao', to=settings.AUTH_USER_MODEL)),
                ('san_bong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlysan.sanbong')),
            ],
        ),
    ]
