# Generated by Django 6.0.3 on 2026-03-31 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='loai',
            field=models.CharField(choices=[('DO_AN', 'Đồ ăn/Nước uống'), ('THUE_DO', 'Thuê đồ (Áo, Bóng, Giày...)')], default='DO_AN', max_length=20),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='thoi_luong',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='tien_coc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='gia_tien',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='gia',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
