# Generated by Django 6.0.3 on 2026-03-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0002_sanpham_loai_alter_datsan_thoi_luong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='so_luong',
            field=models.IntegerField(default=0),
        ),
    ]
