# Generated by Django 6.0.3 on 2026-03-31 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0003_sanpham_so_luong'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung thông báo')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('is_pin', models.BooleanField(default=False, verbose_name='Ghim lên đầu')),
                ('nguoi_dang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
