# Generated by Django 6.0.3 on 2026-03-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0004_thongbao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('don_dat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_dv', to='quanlysan.datsan')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlysan.sanpham')),
            ],
        ),
    ]
