# Generated by Django 6.0.3 on 2026-04-01 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0005_chitietdichvu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datsan',
            name='dich_vu_kem',
        ),
        migrations.RemoveField(
            model_name='diadiem',
            name='mota',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='loai',
        ),
        migrations.AddField(
            model_name='diadiem',
            name='mo_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chitietdichvu',
            name='so_luong',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='sdt',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='thoi_luong',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='tien_coc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=20),
        ),
        migrations.AlterField(
            model_name='diadiem',
            name='dia_chi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diadiem',
            name='kinh_do',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diadiem',
            name='ten_dia_diem',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diadiem',
            name='vi_do',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='gia_tien',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='kinh_do',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='loai_san',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='vi_do',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='gia',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='is_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='noi_dung',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='tieu_de',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.IntegerField(default=5)),
                ('binh_luan', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_danh_gia', to='quanlysan.diadiem')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
