# Generated by Django 6.0.3 on 2026-04-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0006_remove_datsan_dich_vu_kem_remove_diadiem_mota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datsan',
            name='sdt',
            field=models.CharField(max_length=15),
        ),
    ]
