# Generated by Django 5.2.10 on 2026-04-08 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0007_alter_datsan_sdt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='danhgia',
            options={},
        ),
        migrations.RenameField(
            model_name='diadiem',
            old_name='hinh_anh',
            new_name='hinh_anh_dai_dien',
        ),
        migrations.RemoveField(
            model_name='datsan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='datsan',
            name='tien_coc',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='nguoi_dang',
        ),
        migrations.AddField(
            model_name='sanpham',
            name='dia_diem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kho_hang', to='quanlysan.diadiem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanbong',
            name='danh_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlysan.danhmucsan'),
        ),
        migrations.CreateModel(
            name='HinhAnhDiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.ImageField(upload_to='dia_diem_gallery/')),
                ('dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_anh', to='quanlysan.diadiem')),
            ],
        ),
        migrations.CreateModel(
            name='TimDoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField()),
                ('trinh_do', models.CharField(choices=[('YEU', 'Yếu'), ('TB', 'Trung bình'), ('KHA', 'Khá/Mạnh')], max_length=50)),
                ('sdt_lien_he', models.CharField(max_length=15)),
                ('noi_dung', models.TextField()),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('dia_diem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlysan.diadiem')),
                ('nguoi_dang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
