# Generated by Django 5.2.10 on 2026-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0008_danhmucsan_alter_danhgia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datsan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='datsan',
            name='tien_coc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
