# Generated by Django 5.2.10 on 2026-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0009_datsan_created_at_datsan_tien_coc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanbong',
            name='kinh_do',
        ),
        migrations.RemoveField(
            model_name='sanbong',
            name='vi_do',
        ),
    ]
