# Generated by Django 5.2.10 on 2026-04-08 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0010_remove_sanbong_kinh_do_remove_sanbong_vi_do'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timdoi',
            name='dia_diem',
        ),
        migrations.RemoveField(
            model_name='timdoi',
            name='noi_dung',
        ),
        migrations.RemoveField(
            model_name='timdoi',
            name='thoi_gian',
        ),
        migrations.AddField(
            model_name='timdoi',
            name='doi_thu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keo_nhan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timdoi',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timdoi',
            name='gio_bat_dau',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timdoi',
            name='ngay_da',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timdoi',
            name='san_bong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quanlysan.sanbong'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timdoi',
            name='thoi_luong',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='timdoi',
            name='trang_thai',
            field=models.CharField(choices=[('DANG_TIM', 'Đang tìm đối'), ('DA_CAP', 'Đã cáp kèo')], default='DANG_TIM', max_length=20),
        ),
        migrations.AlterField(
            model_name='timdoi',
            name='nguoi_dang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keo_tao', to=settings.AUTH_USER_MODEL),
        ),
    ]
