# Generated by Django 5.2.10 on 2026-04-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0011_remove_timdoi_dia_diem_remove_timdoi_noi_dung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanbong',
            name='loai_san',
            field=models.IntegerField(choices=[(5, 'Sân 5 người'), (7, 'Sân 7 người'), (11, 'Sân 11 người')], default=5),
        ),
    ]
