# Generated by Django 6.0.3 on 2026-04-15 04:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0012_alter_sanbong_loai_san'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hinhanhdiadiem',
            old_name='anh',
            new_name='hinh_anh',
        ),
        migrations.AddField(
            model_name='hinhanhdiadiem',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hinhanhdiadiem',
            name='dia_diem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_hinh_anh', to='quanlysan.diadiem'),
        ),
    ]
