# Generated by Django 5.2.10 on 2026-04-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0013_rename_anh_hinhanhdiadiem_hinh_anh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongTinGioiThieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de_hero', models.CharField(default='Về Chúng Tôi', max_length=255)),
                ('mo_ta_hero', models.TextField(default='Nền tảng đặt sân bóng đá tiện lợi...')),
                ('tam_nhin_su_menh', models.TextField(blank=True, null=True)),
                ('noi_dung_chinh', models.TextField(blank=True, null=True)),
                ('feature_1_title', models.CharField(default='Nhanh chóng', max_length=100)),
                ('feature_1_desc', models.CharField(default='Đặt sân 24/7 chỉ với 30 giây.', max_length=255)),
                ('feature_2_title', models.CharField(default='Cáp kèo dễ dàng', max_length=100)),
                ('feature_2_desc', models.CharField(default='Hệ thống tìm đối thủ thông minh.', max_length=255)),
                ('feature_3_title', models.CharField(default='Uy tín 100%', max_length=100)),
                ('feature_3_desc', models.CharField(default='Cam kết giữ sân, không lo bị hủy.', max_length=255)),
                ('feature_4_title', models.CharField(default='Hỗ trợ tận tình', max_length=100)),
                ('feature_4_desc', models.CharField(default='Chăm sóc khách hàng liên tục.', max_length=255)),
            ],
        ),
    ]
