# Generated by Django 5.2.10 on 2026-04-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0014_thongtingioithieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtingioithieu',
            name='hinh_anh_chinh',
            field=models.ImageField(blank=True, null=True, upload_to='gioi_thieu/', verbose_name='Ảnh minh họa nội dung'),
        ),
        migrations.AddField(
            model_name='thongtingioithieu',
            name='hinh_anh_hero',
            field=models.ImageField(blank=True, null=True, upload_to='gioi_thieu/', verbose_name='Ảnh bìa trang (Hero Background)'),
        ),
        migrations.AlterField(
            model_name='thongtingioithieu',
            name='mo_ta_hero',
            field=models.TextField(default='Nền tảng đặt sân bóng đá tiện lợi...', verbose_name='Mô tả ngắn (Hero)'),
        ),
        migrations.AlterField(
            model_name='thongtingioithieu',
            name='noi_dung_chinh',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung chi tiết'),
        ),
        migrations.AlterField(
            model_name='thongtingioithieu',
            name='tam_nhin_su_menh',
            field=models.TextField(blank=True, null=True, verbose_name='Tầm nhìn & Sứ mệnh'),
        ),
        migrations.AlterField(
            model_name='thongtingioithieu',
            name='tieu_de_hero',
            field=models.CharField(default='Về Chúng Tôi', max_length=255, verbose_name='Tiêu đề chính'),
        ),
    ]
