# Generated by Django 6.0.3 on 2026-04-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0015_thongtingioithieu_hinh_anh_chinh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datsan',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
